const professions = `
"Vízszerelő"
"Villanyszerelő"
"Kőműves"
"Takarítás"
"Burkoló"
"Kertész"
"Háztartási gép szervíz"
"Szobafestő tapétázó"
"Gázvezeték szerelő"
"Asztalos"
"Statikus"
"Redőny javítás"
"Lakatos"
"Kútfúrás"
"Házi betegápolás"
"Gázkészülék javítás"
"Tetőfedő"
"Autószerelő"
"Hűtőgépszerelő"
"Földmérő térképész"
"Ács"
"Ablakcsere nyílászáró beépítés"
"Klímaszerelés"
"Bádogos"
"Melegburkoló parkettázás"
"Kárpitos"
"Karosszéria lakatos"
"Kertépítés"
"Térkövezés"
"Fűtésszerelés"
"Gipszkarton szerelés"
"Könyvelés"
"Varrónő"
"Pedikűr"
"Teherfuvarozás"
"Generálkivitelezés"
"Autóvillamosság"
"Építész"
"Mosógépszerelő"
"Pszichológus"
"Masszázs"
"Ingatlan értékbecslés"
"Üveges"
"Betonozás"
"Duguláselhárítás"
"Földmunka"
"Sírkő"
"Autófényezés"
"Gyógytornász"
"TV- videó- hifi- DVD-szerelő"
"Építési műszaki ellenőr"
"Automata kapu"
"Bútorszerelő"
"Robogó motor szervíz"
"Zárszerelés"
"Bútorasztalos"
"Cserépkályha"
"Ügyvéd"
"Ezermester"
"Hang- tető- hőszigetelés"
"Jósnő"
"Költöztetés"
"Gyógymasszázs"
"Lomtalanítás"
"Szippantás"
"Hegesztés"
"Fodrász mesterfodrász"
"Angoltanár"
"Energetikai tanúsítvány"
"Kaputelefon szerelés"
"Babysitter"
"Esztergályos"
"Árnyékolástechnika"
"Kábeltévés antenna szerelő"
"Dietetikus"
"Műköröm"
"Személyszállítás"
"Kutyakozmetikus"
"Sittelszállítás"
"Kéménybélelés felújítás"
"Épületgépészet"
"Fakitermelő"
"Csontkovács"
"Kéményseprő"
"Sofőrszolgálat"
"Bejárónő házvezetőnő"
"Matektanár"
"Mobiltelefon szervíz"
"Társasházkezelés"
"Magánnyomozó"
"Épületbontás"
"Rendszergazda informatikus"
"Daruzás"
"Rágcsálóirtás rovarirtás"
"Tolmács fordító"
"Autómentés"
"Kozmetikus"
"Riasztó szerelés"
"Ingatlanközvetítő"
"Kineziológus"
"Laptop szervíz"
"Ipari alpinista ipari búvár"
"Magántanár"
"Esküvői videós"
"Némettanár"
"Autófóliázás"
"Gumiszervíz"
"Napelem napkollektor"
"Nyirokmasszázs"
"Öntözéstechnika"
"Zenész"
"Ablakszigetelés"
"Adótanácsadás"
"Autókozmetika"
"Belsőépítész"
"Sminkes"
"Autóüveg szélvédő javítás"
"Hitelszakértő pénzügyi tanácsadó"
"Lakberendező"
"Számítógép szervíz"
"Személyi edző"
"Szőnyegtisztító"
"Állatorvos"
"Cipész"
"Kandallóépítő"
"Bőrdíszműves"
"Fényképész fotós"
"Futárszolgálat"
"Grafikus"
"Kerékpár szervíz"
"Svédmasszázs"
"Egyéb"
"Energetikai tanácsadás"
"Gépi hímzés"
"Gravírozás"
"Munkavédelmi és tűzvédelmi szakember"
"Talpmasszázs"
"Természetgyógyász"
"Biztonságtechnika"
"Ceremóniamester vőfély"
"Családállítás"
"Kárpittisztító"
"Manikűr"
"Piercing"
"Radiátorszerelés"
"Tánctanár"
"Esküvői fotós"
"Futómű beállítás"
"Garázskapuszerelő"
"Hajhosszabbítás"
"Képkeretezés"
"Könyvkötő"
"Kutyakiképző"
"Ötvös"
"Restaurátor"
"Szempilla hosszabbítás"
"Thai masszázs"
"Videós operatőr"
"Asztrológus"
"Bőrgyógyász"
"Designer"
"Hangtechnika"
"Hostess"
"Közjegyző"
"Kulcsmásolás"
"Manuálterápia"
"Nőgyógyász"
"Programozó"
"Pszichiáter"
"Sminktetoválás"
"Uszodatechnika"
"Befektetési tanácsadó"
"Fizikatanár"
"Gitároktatás"
"Kávéfőzőszerelő"
"Kémiatanár"
"Napelemszerelő"
"Napkollektorszerelő"
"Névjegykártya készítés"
"Online marketing"
"Spanyoltanár"
"Szalagfüggöny"
"Térburkolat tisztítás"
"Tetoválás"
"Akupunktúra"
"Cellulit masszázs"
"Fogorvos"
"Fogyasztó masszázs"
"Honlapkészítés"
"Ingatlanfotózás"
"Jós"
"Látványtervező"
"Magyartanár"
"Mediátor"
"Olasztanár"
"Orosztanár"
"Rendezvényszervező"
"Szájsebész"
"Titkárnő asszisztens"
`;

export default professions;
